In [1]:
from sklearn.datasets import load_boston

In [2]:
bunch =load_boston()

In [3]:
X=bunch.data
y=bunch.target

In [4]:
X.shape

(506, 13)

In [5]:
y.shape

(506,)

In [6]:
bunch.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [7]:
X_crim=X[:,0]

In [9]:
X_crim.shape

(506,)

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [23]:
sl_model=LinearRegression()
X_crim=X_crim.reshape(-1,1)
X_train,X_test,y_train,y_test=train_test_split(X_crim,y)

In [24]:
X_train.shape

(379, 1)

In [17]:
X_test.shape

(127,)

In [25]:
sl_model.fit(X_train,y_train)

LinearRegression()

In [26]:
sl_model.score(X_test,y_test)

0.12812774870828147

In [27]:
from sklearn.metrics import r2_score,mean_squared_error

In [28]:

y_pred=sl_model.predict(X_test)
r2_score(y_test,y_pred)

0.12812774870828147

In [29]:
y_pred-y_test

array([  0.36846588,  -2.33612278,   9.21436856,  -2.15742439,
         1.65400348,   5.36015275,   5.5796049 , -26.24377386,
         2.44995248,  -8.43945427,  -0.60374625,   2.33419911,
         3.38869729,   1.67736034, -10.51143741,   5.79261521,
        12.18419393,   8.83774612,  -3.46126611,   0.16566345,
         2.63943943, -12.33341987,   0.19406269,   6.82218132,
         5.3778632 , -28.44027305,   1.08413831,  -0.34709916,
         5.40708934,  -2.75529769,   3.48515477, -11.31115455,
        -0.7906434 ,   4.66981248,  -1.25805136,   2.0546146 ,
         2.22242352,   2.65382887,  -0.40125885, -19.23433306,
       -22.7284033 ,  -3.67449056,   4.83769224,  -5.82434133,
         5.55739521,   6.66579665,   5.95936626,   1.8826584 ,
         5.7248215 ,  -3.46628792,   6.16258102,   2.69228246,
         1.33432221,   1.85597054,  -2.55173858,   8.02838471,
         5.21827538,  11.0574103 ,   6.68852667,   8.87635111,
        -0.40779699,   3.94280172,  -6.94728948,   7.72

In [30]:
import numpy as np

In [34]:
np.hstack([y_pred.reshape(-1,1),y_test.reshape(-1,1)])

array([[ 24.06846588,  23.7       ],
       [ 24.06387722,  26.4       ],
       [ 22.61436856,  13.4       ],
       [ 21.54257561,  23.7       ],
       [ 22.45400348,  20.8       ],
       [ 17.36015275,  12.        ],
       [ 23.7796049 ,  18.2       ],
       [-15.84377386,  10.4       ],
       [ 21.54995248,  19.1       ],
       [ 24.06054573,  32.5       ],
       [ 24.09625375,  24.7       ],
       [ 24.03419911,  21.7       ],
       [ 24.08869729,  20.7       ],
       [ 24.07736034,  22.4       ],
       [ 24.08856259,  34.6       ],
       [ 20.29261521,  14.5       ],
       [ 24.08419393,  11.9       ],
       [ 24.03774612,  15.2       ],
       [ 24.03873389,  27.5       ],
       [ 23.46566345,  23.3       ],
       [ 19.73943943,  17.1       ],
       [ 24.06658013,  36.4       ],
       [ 24.09406269,  23.9       ],
       [ 22.92218132,  16.1       ],
       [ 24.0778632 ,  18.7       ],
       [ 21.55972695,  50.        ],
       [ 23.88413831,  22.8       ],
 

In [35]:
import pandas as pd

In [36]:
df=pd.DataFrame(
    np.hstack([y_pred.reshape(-1,1),y_test.reshape(-1,1)]),
    columns=["Predicted_price","Actual_price"])

In [37]:
df

Predicted_price  Actual_price
0          24.068466          23.7
1          24.063877          26.4
2          22.614369          13.4
3          21.542576          23.7
4          22.454003          20.8
..               ...           ...
122        17.669820          10.2
123        24.065642          19.7
124        20.939926          13.4
125        24.023949          23.1
126        24.078200          23.9

[127 rows x 2 columns]

In [38]:
df["error"]=df.Actual_price-df.Predicted_price

In [39]:
df

Predicted_price  Actual_price     error
0          24.068466          23.7 -0.368466
1          24.063877          26.4  2.336123
2          22.614369          13.4 -9.214369
3          21.542576          23.7  2.157424
4          22.454003          20.8 -1.654003
..               ...           ...       ...
122        17.669820          10.2 -7.469820
123        24.065642          19.7 -4.365642
124        20.939926          13.4 -7.539926
125        24.023949          23.1 -0.923949
126        24.078200          23.9 -0.178200

[127 rows x 3 columns]

In [42]:
(df.error**2/df.shape[0]).sum()

62.259380667851104

In [40]:
df.shape

(127, 3)

In [44]:
(df.error**2).sum()/df.shape[0]

62.25938066785113

In [45]:
mean_squared_error(y_test,y_pred)

62.25938066785113

# Multiple Linear Regression

In [46]:
bunch.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [47]:
X_crim_rm=X[:,[0,5]]

In [48]:
X_crim_rm.shape

(506, 2)

In [51]:
ml_model =LinearRegression()
X_train,X_test,y_train,y_test=train_test_split(X_crim_rm,y)
ml_model.fit(X_train,y_train)
y_pred=ml_model.predict(X_test)
score = r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
print(f"Score: {score*100}\nMSE: {mse}")
print(ml_model.coef_)
print(ml_model.intercept_)


Score: 54.36532951448652
MSE: 38.592662792325505
[-0.25834246  8.44642499]
-29.46732760939827


In [56]:
X_test[0]

array([0.06588, 7.765  ])

In [53]:
y_pred[0]

36.102142847233125

In [57]:
-29.46-(0.258*X_test[0][0])+(8.446*X_test[0][1])

36.10619296

In [58]:
def get_linear_model(X,y):
    ml_model =LinearRegression()
    X_train,X_test,y_train,y_test=train_test_split(X,y)
    ml_model.fit(X_train,y_train)
    y_pred=ml_model.predict(X_test)
    score = r2_score(y_test,y_pred)
    mse=mean_squared_error(y_test,y_pred)
    print(f"Score: {score*100}\nMSE: {mse}")
    print(ml_model.coef_)
    print(ml_model.intercept_)

    

In [59]:
get_linear_model(X_crim_rm,y)

Score: 45.340537705450366
MSE: 50.6794855162529
[-0.30210796  8.10010695]
-27.495270037939736


In [60]:
get_linear_model(X[:,[0,1,5]],y)

Score: 63.1001410226887
MSE: 30.583049240582888
[-0.24117187  0.05286683  7.33685571]
-23.24761532617828
