In [1]:
! pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.2/21.2 MB 9.5 MB/s eta 0:00:00:00:0100:01

[notice] A new release of pip is available: 23.1.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [5]:
list1 = [2,4,56,7,8]
list2 =[2,45,6,7,8]
# result =[4,49,62,14,16]
result =[]
# method 1
for i in range(len(list1)):
    result.append(list1[i]+list2[i])
print(result)


[4, 49, 62, 14, 16]


In [6]:
zip(list1,list2)

In [7]:
list(zip(list1,list2))

[(2, 2), (4, 45), (56, 6), (7, 7), (8, 8)]

In [9]:
result1=[]
for element in zip(list1,list2):
#     print(element)
    result1.append(element[0]+element[1])
print(result1)

[4, 49, 62, 14, 16]


In [ ]:
result1=[]
for element in zip(list1,list2):
#     print(element)
    result1.append(element[0]+element[1])
print(result1)

In [10]:
p=[4,5]

In [11]:
p[0]

4

In [12]:
p[1]

5

In [13]:
q,r=p

In [14]:
q

4

In [15]:
r

5

In [16]:
c=[3,5,6,7]
a,b,d,e=c

In [17]:
a

3

In [18]:
b

5

In [19]:
d

6

In [20]:
e

7

In [21]:
c

[3, 5, 6, 7]

In [22]:
a,v=c

ValueError: too many values to unpack (expected 2)

In [24]:
a,v,*r=c

In [25]:
a

3

In [26]:
v

5

In [27]:
r

[6, 7]

In [28]:
result2=[]
for x,y in zip(list1,list2):
#     print(element)
    result2.append(x+y)
print(result2)

[4, 49, 62, 14, 16]


In [29]:
import numpy as np

In [31]:
type(list1)

list

In [32]:
type(list2)

list

In [33]:
list1_np=np.array(list1)
list2_np=np.array(list2)

In [34]:
list1_np

array([ 2,  4, 56,  7,  8])

In [35]:
type(list1_np)

numpy.ndarray

In [36]:
list1_np+list2_np

array([ 4, 49, 62, 14, 16])

In [37]:
list1_np*list2_np

array([  4, 180, 336,  49,  64])

In [38]:
list1_np

array([ 2,  4, 56,  7,  8])

In [39]:
list2_np

array([ 2, 45,  6,  7,  8])

In [40]:
list1_np*5

array([ 10,  20, 280,  35,  40])

In [41]:
list2_np**2

array([   4, 2025,   36,   49,   64])

In [42]:
list1+list2

[2, 4, 56, 7, 8, 2, 45, 6, 7, 8]

In [43]:
list1*2

[2, 4, 56, 7, 8, 2, 4, 56, 7, 8]

In [44]:
np.array((3,5,6))

array([3, 5, 6])

In [45]:
np.array({3,4,5,6,7})

array({3, 4, 5, 6, 7}, dtype=object)

In [48]:
a=np.array([3,4,5,6,8])
b=np.array([[2,4],[4,6],[1,4]])

In [47]:
a

array([3, 4, 5, 6, 8])

In [49]:
b

array([[2, 4],
       [4, 6],
       [1, 4]])

In [50]:
a.size

5

In [51]:
b.size

6

In [52]:
a.shape

(5,)

In [53]:
b.shape

(3, 2)

In [54]:
a.ndim

1

In [55]:
b.ndim

2

In [56]:
a.dtype

dtype('int64')

In [57]:
b.dtype

dtype('int64')

In [58]:
c=np.array([3,5,6.9,19])

In [59]:
c.dtype

dtype('float64')

In [60]:
c

array([ 3. ,  5. ,  6.9, 19. ])

In [61]:
d=np.array([12,"4",67,4.6])

In [62]:
d

array(['12', '4', '67', '4.6'], dtype='<U32')

In [63]:
np.zeros(4)

array([0., 0., 0., 0.])

In [65]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [66]:
np.zeros((4,2),dtype="int")

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [67]:
np.ones(3)

array([1., 1., 1.])

In [68]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [71]:
np.identity((3,5))

TypeError: 'tuple' object cannot be interpreted as an integer

In [72]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [78]:
x=np.linspace(1,100)

In [80]:
x.shape

(50,)

In [81]:
x

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [82]:
99/49

2.020408163265306

In [83]:
np.linspace(1,100,15)

array([  1.        ,   8.07142857,  15.14285714,  22.21428571,
        29.28571429,  36.35714286,  43.42857143,  50.5       ,
        57.57142857,  64.64285714,  71.71428571,  78.78571429,
        85.85714286,  92.92857143, 100.        ])

In [84]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [85]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
np.arange(2,10,3)

array([2, 5, 8])

In [87]:
np.arange(2,10,1.5)

array([2. , 3.5, 5. , 6.5, 8. , 9.5])

In [88]:
np.arange(1.3,10,1.5)

array([1.3, 2.8, 4.3, 5.8, 7.3, 8.8])

In [89]:
c

array([ 3. ,  5. ,  6.9, 19. ])

In [90]:
print(c)

[ 3.   5.   6.9 19. ]


In [91]:
np.random.randint(1,4)

2

In [92]:
np.random.randint(1,4,10)

array([3, 1, 1, 1, 3, 2, 3, 1, 1, 1])

In [93]:
np.random.randint(1,100,(4,6))

array([[40, 39, 97, 39, 41, 50],
       [65, 61, 70, 25, 67, 55],
       [76, 36, 67, 50, 79,  7],
       [88, 10, 22,  4, 31, 23]])

## Operations on numpy arrays

In [94]:
a= np.random.randint(1,10,4)
b= np.random.randint(1,10,4)

In [95]:
a

array([6, 6, 1, 9])

In [96]:
b

array([7, 4, 7, 8])

In [97]:
a+b

array([13, 10,  8, 17])

In [98]:
a-b

array([-1,  2, -6,  1])

In [99]:
a/b

array([0.85714286, 1.5       , 0.14285714, 1.125     ])

In [100]:
a*b

array([42, 24,  7, 72])

In [101]:
a*2

array([12, 12,  2, 18])

In [102]:
b**3

array([343,  64, 343, 512])

In [103]:
a

array([6, 6, 1, 9])

In [104]:
a%2

array([0, 0, 1, 1])

In [105]:
a%7

array([6, 6, 1, 2])

In [107]:
a//5

array([1, 1, 0, 1])

In [108]:
a+2

array([ 8,  8,  3, 11])

In [109]:
b=np.ones(4)*2

In [110]:
b

array([2., 2., 2., 2.])

In [111]:
a+b

array([ 8.,  8.,  3., 11.])

In [112]:
a

array([6, 6, 1, 9])

In [113]:
b=np.random.randint(1,5,(3,4))

In [114]:
b

array([[4, 1, 4, 1],
       [4, 2, 4, 4],
       [3, 2, 2, 2]])

In [115]:
list1_np

array([ 2,  4, 56,  7,  8])

In [116]:
a

array([6, 6, 1, 9])

In [117]:
a+list1_np

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [118]:
a

array([6, 6, 1, 9])

In [119]:
b

array([[4, 1, 4, 1],
       [4, 2, 4, 4],
       [3, 2, 2, 2]])

In [120]:
a+b

array([[10,  7,  5, 10],
       [10,  8,  5, 13],
       [ 9,  8,  3, 11]])

In [121]:
c1=np.random.randint(1,6,(4,4))

In [133]:
c2=np.random.randint(1,6,(1,4))

In [127]:
c1

array([[4, 5, 5, 5],
       [4, 4, 5, 4],
       [3, 1, 5, 3],
       [3, 1, 3, 2]])

In [134]:
c2

array([[4, 2, 5, 3]])

In [135]:
c1+c2

array([[ 8,  7, 10,  8],
       [ 8,  6, 10,  7],
       [ 7,  3, 10,  6],
       [ 7,  3,  8,  5]])

In [136]:
np.sin(list1_np)

array([ 0.90929743, -0.7568025 , -0.521551  ,  0.6569866 ,  0.98935825])

In [137]:
list1_np

array([ 2,  4, 56,  7,  8])

In [138]:
np.exp(list1)

array([7.38905610e+00, 5.45981500e+01, 2.09165950e+24, 1.09663316e+03,
       2.98095799e+03])