In [1]:
import numpy as np
ages = np.random.randint(16,90,6)

In [2]:
ages

array([60, 59, 19, 32, 75, 57])

In [3]:
mean = ages.mean()

In [4]:
mean

50.333333333333336

In [5]:
age_more_than_mean= ages>mean

In [6]:
age_more_than_mean

array([ True,  True, False, False,  True,  True])

In [7]:
ages[age_more_than_mean]

array([60, 59, 75, 57])

In [8]:
h=[2,4,5,6,7,5]
squares =[]
for x in h:
    squares.append(x**2)
print(squares)

[4, 16, 25, 36, 49, 25]


In [9]:
[y**2 for y in h]

[4, 16, 25, 36, 49, 25]

In [12]:
my_max=ages.max()

In [13]:
my_min=ages.min()

In [20]:
ages>my_min

array([ True,  True, False,  True,  True,  True])

In [21]:
ages<my_max

array([ True,  True,  True,  True, False,  True])

In [22]:
# ages>my_min==ages<my_max

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [23]:
ages

array([60, 59, 19, 32, 75, 57])

In [24]:
ages>34

array([ True,  True, False, False,  True,  True])

In [32]:
ages[ages>34]

array([60, 59, 75, 57])

In [36]:
ages[ages<=34]

array([19, 32])

In [37]:
scores=np.random.randint(0,100,(5,3))

In [38]:
scores

array([[49, 20, 80],
       [27, 17, 51],
       [46, 49, 79],
       [66, 65, 19],
       [53, 34, 35]])

In [39]:
ages_new =[]
for i in range(3):
    value=int(input(""))
    ages_new.append(value)
ages_np=np.array(ages_new)

6
8
12


In [40]:
ages_np

array([ 6,  8, 12])

In [41]:
scores.mean()

46.0

In [42]:
scores.min()

17

In [43]:
scores.max()

80

In [44]:
scores.var()

398.0

In [45]:
scores

array([[49, 20, 80],
       [27, 17, 51],
       [46, 49, 79],
       [66, 65, 19],
       [53, 34, 35]])

In [46]:
scores.std()

19.949937343260004

In [47]:
scores.mean()

46.0

In [48]:
scores.mean(axis=0)

array([48.2, 37. , 52.8])

In [50]:
scores.min(axis=1)

array([20, 17, 46, 19, 34])

In [51]:
ages

array([60, 59, 19, 32, 75, 57])

In [52]:
ages[0]

60

In [53]:
ages[-1]

57

In [55]:
ages.argmin()

2

In [56]:
ages

array([60, 59, 19, 32, 75, 57])

In [57]:
scores

array([[49, 20, 80],
       [27, 17, 51],
       [46, 49, 79],
       [66, 65, 19],
       [53, 34, 35]])

In [59]:
scores[1]

array([27, 17, 51])

In [60]:
scores[1][1]

17

In [61]:
scores[3][2]

19

In [62]:
scores[3,2]

19

In [63]:
scores[1,1]

17

In [64]:
a=[[2,3],[4,5],[5,4]]

In [65]:
a

[[2, 3], [4, 5], [5, 4]]

In [66]:
print(a)

[[2, 3], [4, 5], [5, 4]]


In [70]:
print(*a,sep="\n")

[2, 3]
[4, 5]
[5, 4]


In [71]:
print([2,3,5])

[2, 3, 5]


In [73]:
print(*[2,3,5],sep="==")

2==3==5


In [74]:
print(*[2,3,5],sep="\n")

2
3
5


In [75]:
a[1][1]

5

In [76]:
ages

array([60, 59, 19, 32, 75, 57])

In [77]:
ages[0:3]

array([60, 59, 19])

In [78]:
ages[0:3:2]

array([60, 19])

In [79]:
scores

array([[49, 20, 80],
       [27, 17, 51],
       [46, 49, 79],
       [66, 65, 19],
       [53, 34, 35]])

In [80]:
scores[1:3,:]

array([[27, 17, 51],
       [46, 49, 79]])

In [82]:
scores[1:3,0]

array([27, 46])

In [83]:
scores[1:3,0:2]

array([[27, 17],
       [46, 49]])

In [84]:
ages

array([60, 59, 19, 32, 75, 57])

In [ ]:
# Fancy index

In [85]:
ages[[0,1,5]]

array([60, 59, 57])

In [86]:
scores[0]

array([49, 20, 80])

In [87]:
scores[[1],[2]]

array([51])

In [88]:
scores[[1,2],[2,0]]

array([51, 46])

In [90]:
course1=scores[:,0]

In [91]:
course1

array([49, 27, 46, 66, 53])

In [93]:
passed_array=course1>=40

In [94]:
passed_array

array([ True, False,  True,  True,  True])

In [95]:
course1[passed_array]

array([49, 46, 66, 53])